-- MOVED — do not apply this file by hand.
--
-- The Schema Intelligence DDL (usage_event, label_profile, property_ranking,
-- relationship_profile) now lives in Python and is applied automatically on every
-- startup:
--
--     scidk/services/schema_intelligence.py
--         SI_TABLE_DDL
--         SI_ADDED_COLUMNS
--         ensure_schema_intelligence_tables(conn)   <- called from create_app()
--
-- These tables belong to scidk_settings.db, not files.db, so they are deliberately
-- NOT routed through scidk/core/migrations.py.
--
-- This file previously held a copy of the DDL that no code ever executed; the
-- tables existed only where someone had applied it by hand. Applying a copy from
-- here again would reintroduce the drift. Left as a pointer rather than deleted
-- because it has been applied manually on at least one deployment.
