"""Turn :class:`~plugins.nih_dms.graph_facts.GraphFacts` into DMS plan markdown.

A pure function of the facts — no database, no clock beyond the timestamp it is
handed — so the prose can be tested by constructing facts directly.

Four sections, in the order NIH numbers them, because the draft is meant to be
pasted into DMPTool field by field and matching its headings is what makes that a
copy rather than a re-read:

===============================  ==================================
This plugin's section            NIH DMS Policy element
===============================  ==================================
Data Types                       Element 1 — Data Type
Standards                        Element 3 — Standards
Preservation                     Element 4 — Data Preservation,
                                 Access, and Associated Timelines
Access                           Element 5 — Access, Distribution,
                                 or Reuse Considerations
===============================  ==================================

Elements 2 and 6 (tools/code, and oversight) are not generated: nothing in the
graph knows who signs off on a plan or which analysis code produced a result, and
inventing that text is exactly the failure mode this plugin exists to avoid.

Two rules run through all of it:

* **Every number is real.** Counts, byte totals, formats and modalities come from
  the graph. Where a fact is absent, the draft says it is absent and asks for it.
* **Every human decision is a bracketed placeholder.** ``[REPOSITORY_NAME]``,
  ``[RETENTION_PERIOD]`` and friends are upper-case in brackets so a reviewer can
  find them by eye and by search, and so an unedited draft can never be mistaken
  for a finished plan.
"""
from __future__ import annotations

from datetime import datetime, timezone
from typing import Iterable, List, Optional, Sequence

from . import config as cfg
from .graph_facts import GraphFacts, ModalityFinding

#: Byte-size units. Binary multiples, labelled as such.
_UNITS: Sequence[str] = ('bytes', 'KiB', 'MiB', 'GiB', 'TiB', 'PiB')


def human_bytes(value: int) -> str:
    """``8076257245704`` -> ``'7.35 TiB'``. Three significant figures is plenty."""
    size = float(max(int(value or 0), 0))
    for unit in _UNITS:
        if size < 1024 or unit == _UNITS[-1]:
            if unit == 'bytes':
                return f'{int(size)} bytes'
            return f'{size:.2f} {unit}'
        size /= 1024
    return f'{size:.2f} {_UNITS[-1]}'  # pragma: no cover - loop always returns


def _n(value: int) -> str:
    """Thousands-separated integer."""
    return f'{int(value or 0):,}'


def _pct(part: int, whole: int) -> str:
    """``part`` as a percentage of ``whole``, or ``'0%'`` when there is no whole."""
    if not whole:
        return '0%'
    share = 100.0 * float(part) / float(whole)
    if 0 < share < 0.1:
        return '<0.1%'
    return f'{share:.1f}%'


def _extension_label(extension: str) -> str:
    """Display form of an extension; empty means the file had none."""
    return f'`{extension}`' if extension else '*(no extension)*'


def _extension_label_plain(extension: str) -> str:
    """As :func:`_extension_label`, but safe to nest inside emphasised text.

    ``*(no extension)*`` inside an italic paragraph closes the outer emphasis and
    renders as literal asterisks, so the italic form is dropped here.
    """
    return f'`{extension}`' if extension else '(no extension)'


def _values_phrase(finding: ModalityFinding, limit: int = 6) -> str:
    """A few of a finding's values, commonest first, as inline prose."""
    shown = [value for value, _ in finding.values[:limit]]
    text = ', '.join(shown)
    remainder = len(finding.values) - len(shown)
    if remainder > 0 or finding.truncated:
        text += ', …'
    return text


# ------------------------------------------------------------------ preamble


def _preamble(facts: GraphFacts, generated_at: str) -> List[str]:
    """Title, provenance, and the warning that this is a draft."""
    lines = [
        '# Data Management and Sharing Plan — Draft',
        '',
        '> **This is a generated draft, not a submission.** Every figure below was read '
        'from this instance\'s knowledge graph at the time shown. Every `[PLACEHOLDER]` '
        'is a decision a person has to make. Read the whole document, replace the '
        'placeholders, and delete anything that does not apply to your award before '
        'submitting.',
        '',
        f'*Generated by SciDK from the live graph on {generated_at}.*',
        '',
    ]

    if facts.format_sample_limit:
        lines += [
            f'> **Sampled, not exhaustive.** The file breakdown in this draft reads only the '
            f'first {_n(facts.format_sample_limit)} `:File` nodes the store returns, which is '
            f'not a random sample — store order is not sample order, and formats held mostly '
            f'in later-written files can be under-reported or missed. Regenerate without a '
            f'sample limit before submitting.',
            '',
        ]

    if facts.warnings:
        lines.append('> **Notes from generation:**')
        lines += [f'> - {warning}' for warning in facts.warnings]
        lines.append('')

    return lines


# ------------------------------------------------- Element 1 — Data Types


def _phi_warning(facts: GraphFacts) -> List[str]:
    """The identifiability paragraph. Only rendered when something matched."""
    confirmed = facts.confirmed_phi_hits
    weak = [h for h in facts.phi_hits if h.evidence == 'property_key_store']

    lines: List[str] = ['#### ⚠ Potentially identifiable data detected', '']

    if confirmed:
        lines += [
            'This graph holds property names that commonly carry direct identifiers. '
            'The properties below were found on current data or named in the schema layer:',
            '',
        ]
        for hit in confirmed:
            where = 'schema layer' if hit.evidence == 'label_profile' else hit.location
            lines.append(f'- `{hit.property_name}` — on {where}')
        lines.append('')

    if weak:
        names = ', '.join(f'`{h.property_name}`' for h in weak)
        lines += [
            f'The database\'s property key store also contains {names}, which no current node '
            'or relationship carries. That usually means such data was present and has since '
            'been deleted — worth confirming, but not in itself evidence that identifiers are '
            'held now.',
            '',
        ]

    if confirmed:
        lines += [
            '**Consequences for this plan, which you must resolve before submission:**',
            '',
            '- Data in this collection are likely to constitute individually identifiable '
            'private information. De-identification under HIPAA (45 CFR 164.514) or an '
            'equivalent standard is required before any release, and the plan must state '
            'which standard and which method were used.',
            '- Direct identifiers must be removed or replaced with study-specific codes, and '
            'the key linking codes to identities must be described here as retained '
            'separately and not shared.',
            '- Check whether the consent under which these data were collected permits broad '
            'sharing. If it does not, say so in Element 5 and justify the limitation — NIH '
            'accepts consent-based limits when they are explained.',
            '- Controlled access through a repository with a Data Access Committee is the '
            'usual answer for human subjects data. If you intend open access, state the '
            'basis for concluding the data are not identifiable.',
            '- If a Certificate of Confidentiality applies, its terms constrain disclosure '
            'and belong in this plan.',
            '',
            f'*Detection matches property names against a configurable list '
            f'({", ".join("`" + n + "`" for n in cfg.PHI_PROPERTY_NAMES)}). It is a prompt to '
            f'look, not a determination — it cannot find an identifier hidden in a free-text '
            f'field or an unusually named column, and it does not judge whether the data are '
            f'in fact identifiable. A human review is still required.*',
            '',
        ]
    else:
        lines += [
            '*No property on current data matched. A human review is still required — see '
            'the caveat below.*',
            '',
        ]

    return lines


def _no_phi_note(facts: GraphFacts) -> List[str]:
    """What to say when the identifier scan came back clean."""
    scanned = 'any property name in the graph'
    if facts.profiled_labels:
        scanned += (
            f', nor in the {len(facts.profiled_labels)} curated label profile(s) in the '
            f'schema layer'
        )

    return [
        '#### Identifiability',
        '',
        f'No known direct identifier '
        f'({", ".join("`" + n + "`" for n in cfg.PHI_PROPERTY_NAMES)}) matched {scanned}. '
        f'**This is not a finding that the data are de-identified.** The check compares '
        f'property names only: it cannot see an identifier inside a free-text note, a '
        f'filename, an image header, or a column named in a way it does not recognise. '
        f'Confirm the identifiability of these data with your IRB or privacy office and '
        f'record the conclusion here.',
        '',
    ]


def _data_types_section(facts: GraphFacts) -> List[str]:
    """Element 1 — what data there is, how much, and in what formats."""
    lines = [
        '## Element 1: Data Type',
        '',
        '### A. Types and amount of scientific data to be generated and/or used',
        '',
    ]

    if not facts.label_counts:
        lines += [
            'The graph is reachable but holds no nodes, so there is nothing to describe here '
            'yet. Scan a data directory and commit the scan to Neo4j, then regenerate this '
            'draft.',
            '',
        ]
        return lines

    # Summary sentence: real totals, in prose, because that is what a reviewer reads.
    entity_kinds = len(facts.label_counts)
    if facts.file_count:
        lines += [
            f'This project\'s data are managed in a SciDK knowledge graph describing '
            f'**{_n(facts.file_count)} data files totalling {human_bytes(facts.file_bytes)}**, '
            f'organised across {_n(entity_kinds)} kinds of catalogued entity '
            f'({_n(facts.total_nodes)} records in total). The graph records what each file is, '
            f'where it came from, and which samples, datasets and processing runs it relates '
            f'to; the paragraphs below are generated from that record.',
            '',
        ]
    else:
        lines += [
            f'This project\'s data are managed in a SciDK knowledge graph of '
            f'{_n(facts.total_nodes)} records across {_n(entity_kinds)} kinds of catalogued '
            f'entity. No file-level index has been committed to the graph yet, so file counts '
            f'and volumes are not stated below.',
            '',
        ]

    # Entity inventory.
    lines += [
        '**Catalogued entities.** The following entity types are present, with exact counts:',
        '',
        '| Entity type | Records |',
        '| --- | --- |',
    ]
    lines += [f'| `{label}` | {_n(count)} |' for label, count in facts.label_counts]
    lines.append('')
    if facts.labels_truncated:
        lines += [
            f'*More than {cfg.MAX_LABELS} entity types exist; the {cfg.MAX_LABELS} listed are '
            f'the ones reported.*',
            '',
        ]
    lines += [
        '*Counts are per entity type. A record carrying more than one type is counted under '
        'each, so the total above can exceed the number of distinct records.*',
        '',
    ]

    # Formats.
    if facts.formats:
        lines += [
            '**File types and volumes.** The data files break down by format as follows:',
            '',
            '| Format | Files | Share | Volume |',
            '| --- | --- | --- | --- |',
        ]
        for row in facts.formats:
            name = row.format_name if row.format_name != 'Unclassified' else 'Unclassified'
            lines.append(
                f'| {_extension_label(row.extension)} — {name} | {_n(row.count)} | '
                f'{_pct(row.count, facts.file_count)} | {human_bytes(row.bytes)} |'
            )
        lines.append('')
        if facts.formats_truncated:
            lines += [
                f'*The {cfg.MAX_FORMATS} commonest formats are shown; a long tail of rarer '
                f'formats also exists. Totals in the paragraph above cover every file, not '
                f'only the rows listed.*',
                '',
            ]

        unclassified = [r for r in facts.formats if r.format_name == 'Unclassified']
        if unclassified:
            names = ', '.join(_extension_label_plain(r.extension) for r in unclassified)
            count = len(unclassified)
            subject = ('One of the listed formats is' if count == 1
                       else f'{count} of the listed formats are')
            lines += [
                f'*{subject} not in SciDK\'s format registry: {names}. Identify '
                f'{"it" if count == 1 else "them"} and say what '
                f'{"it is" if count == 1 else "they are"} before submitting — a reviewer will '
                f'ask about an unnamed format holding this much data.*',
                '',
            ]

    # Relationships: the argument that this is organised data, not a pile of files.
    if facts.relationship_counts:
        top = facts.relationship_counts[:6]
        listed = ', '.join(f'`{name}` ({_n(count)})' for name, count in top)
        lines += [
            f'**Structure.** Entities are connected by '
            f'{_n(len(facts.relationship_counts))} kinds of documented relationship, the '
            f'commonest being {listed}. These links are what make the collection navigable '
            f'and reusable: a file can be traced to its sample, its acquisition run and its '
            f'protocol without reference to external notes.',
            '',
        ]

    if facts.collection_profiles:
        for finding in facts.collection_profiles:
            lines += [
                f'**Dataset structure ({finding.source}).** Datasets in this collection are '
                f'organised as: {_values_phrase(finding)}.',
                '',
            ]

    lines += [
        '### B. Scientific data that will be preserved and shared, and the rationale',
        '',
        f'[STATE WHICH OF THE DATA ABOVE WILL BE SHARED.] All data underlying reported '
        f'findings will be preserved and shared. '
        f'[IF YOU INTEND TO SHARE LESS THAN THE FULL COLLECTION — FOR EXAMPLE EXCLUDING '
        f'FAILED ACQUISITIONS, INTERMEDIATE PROCESSING ARTEFACTS, OR CALIBRATION FILES — '
        f'LIST THOSE EXCLUSIONS HERE AND GIVE THE REASON FOR EACH.]',
        '',
        'Metadata describing the full collection — including entities and relationships not '
        'themselves shared — will be published alongside the data so that the scope of what '
        'was collected remains discoverable.',
        '',
    ]

    lines += _phi_warning(facts) if facts.has_phi else _no_phi_note(facts)
    return lines


# --------------------------------------------------- Element 3 — Standards


def _standards_section(facts: GraphFacts) -> List[str]:
    """Element 3 — metadata standards, formats, and the modalities present."""
    lines = [
        '## Element 3: Standards',
        '',
        '### Metadata standards',
        '',
        'Descriptive metadata for this collection is maintained in a SciDK knowledge graph '
        'and published using established standards rather than a project-specific schema:',
        '',
    ]
    lines += [f'- {standard}' for standard in cfg.METADATA_STANDARDS]
    lines += [
        '',
        'Each released dataset is packaged as an **RO-Crate** — a self-describing directory '
        'whose `ro-crate-metadata.json` carries the descriptive metadata as JSON-LD using '
        'schema.org terms. SciDK generates these crates directly from the graph, so the '
        'metadata accompanying a release is the same metadata used to manage the data, not a '
        'summary re-typed at publication time. RO-Crate is a widely adopted community '
        'packaging convention, and a crate remains readable as plain JSON-LD without SciDK.',
        '',
        '### Data standards and file formats',
        '',
    ]

    if facts.formats:
        known = [r for r in facts.formats if r.standard]
        unknown = [r for r in facts.formats if not r.standard]

        if known:
            lines += [
                'The formats present in this collection, and the community standard each '
                'conforms to:',
                '',
                '| Format | Files | Standard |',
                '| --- | --- | --- |',
            ]
            lines += [
                f'| {_extension_label(r.extension)} — {r.format_name} | {_n(r.count)} | '
                f'{r.standard} |'
                for r in known
            ]
            lines.append('')

            vendor = [r for r in known if 'vendor' in (r.standard or '').lower()]
            if vendor:
                names = ', '.join(_extension_label(r.extension) for r in vendor)
                lines += [
                    f'**Vendor formats.** {names} are instrument-native formats. They are '
                    f'retained as acquired, because the original is the authoritative record '
                    f'and re-encoding loses metadata. For public release these will be '
                    f'converted to their open archival counterpart (OME-TIFF or OME-NGFF as '
                    f'appropriate) and released alongside the originals where size permits. '
                    f'[CONFIRM WHICH CONVERSION APPLIES TO YOUR INSTRUMENTS.]',
                    '',
                ]

        if unknown:
            names = ', '.join(_extension_label(r.extension) for r in unknown)
            heading = ('Format without a registered standard' if len(unknown) == 1
                       else 'Formats without a registered standard')
            instruction = (
                '[IDENTIFY THIS FORMAT AND NAME THE STANDARD OR SPECIFICATION IT FOLLOWS, '
                'OR STATE THAT IT WILL BE CONVERTED BEFORE RELEASE.]'
                if len(unknown) == 1 else
                '[IDENTIFY THESE FORMATS AND NAME THE STANDARD OR SPECIFICATION EACH '
                'FOLLOWS, OR STATE THAT THEY WILL BE CONVERTED BEFORE RELEASE.]'
            )
            lines += [f'**{heading}.** {names} {instruction}', '']
    else:
        lines += [
            'No file-level index has been committed to the graph, so the formats in use '
            'cannot be listed. [NAME THE FILE FORMATS THIS PROJECT WILL PRODUCE AND THE '
            'STANDARD EACH CONFORMS TO.]',
            '',
        ]

    if facts.mime_types:
        declared = _pct(facts.mime_known, facts.file_count)
        top = ', '.join(f'`{value}` ({_n(count)})' for value, count in facts.mime_types[:5])
        lines += [
            f'**Media types.** {_n(facts.mime_known)} files ({declared}) carry a recorded '
            f'IANA media type, the commonest being {top}. Media types are recorded during '
            f'indexing where they can be determined; the remainder are typed by format as '
            f'listed above.',
            '',
        ]

    lines += ['### Measurement modalities and assays', '']

    if facts.modalities:
        lines += [
            'The collection\'s own records name the following measurements. These are read '
            'from the graph, so they describe what was actually acquired:',
            '',
        ]
        for finding in facts.modalities:
            where = 'relationship' if finding.on_relationship else 'entity'
            lines.append(
                f'- **{finding.source}** ({where} property) — {_values_phrase(finding)}'
            )
        lines += [
            '',
            '[FOR EACH MODALITY ABOVE, NAME THE STANDARD OR COMMUNITY GUIDELINE ITS METADATA '
            'FOLLOWS — FOR EXAMPLE DICOM FOR CLINICAL IMAGING, OME FOR MICROSCOPY, MIFlowCyt '
            'FOR FLOW CYTOMETRY, MINSEQE FOR SEQUENCING, OR MIAPPE / REMBI WHERE APPLICABLE.] '
            'Where no community standard exists for a modality, the RO-Crate metadata above '
            'documents the acquisition parameters recorded at the instrument.',
            '',
        ]
    else:
        lines += [
            'No property naming a measurement modality or assay was found in the graph. '
            'SciDK looks for properties such as '
            f'{", ".join("`" + p + "`" for p in cfg.MODALITY_PROPERTIES[:6])} and others on '
            'both entities and relationships.',
            '',
            '[NAME THE IMAGING MODALITIES, ASSAYS AND INSTRUMENT PLATFORMS THIS PROJECT USES, '
            'AND THE METADATA STANDARD EACH FOLLOWS.] To have this section generated from the '
            'data instead, record the modality on the relevant entities in the graph — for '
            'example as a `modality` or `assay_type` property — and regenerate this draft.',
            '',
        ]

    return lines


# ------------------------------------------------ Element 4 — Preservation


def _repository_phrase(facts: GraphFacts) -> str:
    """The repository name, or the placeholder plus where to set it."""
    if facts.repository:
        return facts.repository
    return cfg.REPOSITORY_PLACEHOLDER


def _preservation_section(facts: GraphFacts) -> List[str]:
    """Element 4 — repository, timelines, and how the data are packaged."""
    repository = _repository_phrase(facts)
    retention = facts.retention_years or None

    lines = [
        '## Element 4: Data Preservation, Access, and Associated Timelines',
        '',
        '### A. Repository to be used',
        '',
        f'Scientific data and accompanying metadata will be deposited in **{repository}**.',
        '',
    ]

    if not facts.repository:
        lines += [
            f'*{cfg.REPOSITORY_PLACEHOLDER} is not yet configured in this SciDK instance. Set '
            f'it under Settings → Publication (setting key `{cfg.SETTING_REPOSITORY}`) and '
            f'regenerate, or replace the placeholder by hand. NIH expects an established '
            f'discipline-specific repository where one exists for your data type; a generalist '
            f'repository is acceptable where one does not.*',
            '',
        ]

    lines += [
        '### B. How data will be findable and identifiable',
        '',
        'Deposited data will be assigned a persistent identifier by the repository, and that '
        'identifier will be cited in all publications reporting on these data. Each deposit '
        'is accompanied by an RO-Crate metadata document (see Element 3) describing the '
        'entities in the deposit and the relationships between them, so that a third party '
        'can determine what a file is and how it relates to the rest of the collection '
        'without contacting the submitting laboratory.',
        '',
        'The knowledge graph from which this plan was generated is itself exportable as '
        'RO-Crate, allowing the collection\'s structure — not only its files — to be '
        'preserved and cited.',
        '',
        '### C. When data will be shared',
        '',
        'Scientific data underlying a publication will be made available no later than the '
        'date of that publication. Data not associated with a publication will be made '
        'available by the end of the performance period of the award, in accordance with the '
        'NIH Data Management and Sharing Policy.',
        '',
        '### D. How long data will be preserved',
        '',
    ]

    if retention:
        lines += [
            f'Data and metadata will remain available for at least **{retention}** from the '
            f'date of deposit.',
            '',
        ]
    else:
        lines += [
            f'Data and metadata will remain available for at least **'
            f'{cfg.RETENTION_PLACEHOLDER}** from the date of deposit.',
            '',
            f'*{cfg.RETENTION_PLACEHOLDER} is not yet configured in this SciDK instance. Set '
            f'it under Settings → Publication (setting key `{cfg.SETTING_RETENTION_YEARS}`) and '
            f'regenerate, or replace the placeholder by hand. NIH sets no single minimum; '
            f'check your repository\'s retention commitment and your institution\'s records '
            f'policy, and state the longer of the two. Awards involving human subjects '
            f'frequently require longer retention than the repository\'s default.*',
            '',
        ]

    preservation = (
        'Preservation relies on the repository\'s own curation and integrity commitments '
        'rather than on laboratory-held storage.'
    )
    if facts.file_count:
        preservation += (
            ' Locally, files are indexed with size and modification metadata so that a '
            f'missing or altered file can be detected; {human_bytes(facts.file_bytes)} across '
            f'{_n(facts.file_count)} files is currently tracked this way.'
        )
    lines += [preservation, '']

    return lines


# ---------------------------------------------------- Element 5 — Access


_SOVEREIGNTY_PROSE = {
    'raw': 'released as recorded',
    'hidden': 'withheld from all releases',
    'pseudonymized': 'replaced with a study-specific code before release',
    'simulated': 'replaced with values drawn from a matched distribution',
    'randomized': 'randomised before release',
}


def _sharing_modes_prose(facts: GraphFacts) -> List[str]:
    """Access text derived from per-property sharing modes in the schema layer."""
    lines = [
        'Access is governed per property by sharing modes recorded in this instance\'s schema '
        'layer. The treatment of each property on release is therefore already defined and '
        'enforced by the platform rather than left to a manual step:',
        '',
        '| Entity type | Property | On release |',
        '| --- | --- | --- |',
    ]

    withheld: List[str] = []
    transformed: List[str] = []

    for label in sorted(facts.sharing_modes):
        for prop in sorted(facts.sharing_modes[label]):
            mode = facts.sharing_modes[label][prop]
            prose = _SOVEREIGNTY_PROSE.get(mode, f'`{mode}`')
            lines.append(f'| `{label}` | `{prop}` | {prose} |')
            if mode == 'hidden':
                withheld.append(f'`{label}.{prop}`')
            elif mode in ('pseudonymized', 'simulated', 'randomized'):
                transformed.append(f'`{label}.{prop}`')

    lines.append('')

    if withheld:
        lines += [
            f'**Withheld properties.** {", ".join(withheld)} will not appear in any release. '
            f'[STATE WHY EACH IS WITHHELD — CONSENT TERMS, IDENTIFIABILITY, OR THIRD-PARTY '
            f'RESTRICTION.]',
            '',
        ]
    if transformed:
        lines += [
            f'**Transformed properties.** {", ".join(transformed)} are altered before release '
            f'so that the released data remain analytically useful without disclosing the '
            f'underlying values. The transformation applied to each is recorded in the schema '
            f'layer and described in the metadata accompanying the release, so that a '
            f'secondary analyst knows a value is derived rather than measured.',
            '',
        ]

    return lines


def _access_section(facts: GraphFacts) -> List[str]:
    """Element 5 — who may access the data, and under what terms."""
    lines = [
        '## Element 5: Access, Distribution, or Reuse Considerations',
        '',
        '### A. Factors affecting access',
        '',
    ]

    if facts.sharing_modes:
        lines += _sharing_modes_prose(facts)
    elif facts.sharing_mode:
        template = cfg.SHARING_MODES[facts.sharing_mode]
        contact = facts.access_contact or cfg.CONTACT_PLACEHOLDER
        lines += [
            template.format(
                repository=_repository_phrase(facts),
                contact=contact,
            ),
            '',
            f'*Derived from the configured sharing mode '
            f'"{cfg.SHARING_MODE_LABELS.get(facts.sharing_mode, facts.sharing_mode)}" '
            f'(`{cfg.SETTING_SHARING_MODE}`). Review the wording against the consent terms '
            f'under which these data were collected.*',
            '',
        ]
        # Only some modes name a contact; the placeholder note is only relevant
        # when the chosen mode's prose actually asks for one.
        if not facts.access_contact and '{contact}' in template:
            lines += [
                f'*{cfg.CONTACT_PLACEHOLDER} is not configured; set '
                f'`{cfg.SETTING_ACCESS_CONTACT}` under Settings → Publication or replace it '
                f'by hand.*',
                '',
            ]
    else:
        lines += _access_prompt(facts)

    lines += [
        '### B. Whether access will be controlled',
        '',
    ]

    if facts.sharing_modes or facts.sharing_mode:
        lines += [
            '[CONFIRM THE CONTROL MECHANISM: OPEN DOWNLOAD, REGISTERED ACCESS, OR '
            'CONTROLLED ACCESS THROUGH A DATA ACCESS COMMITTEE WITH A DATA USE AGREEMENT.] '
            'Where the data derive from human subjects, controlled access through a '
            'repository operating a Data Access Committee is expected unless the data are '
            'demonstrably not identifiable.',
            '',
        ]
    else:
        lines += [
            '[STATE WHETHER ACCESS WILL BE CONTROLLED, AND BY WHOM.]',
            '',
        ]

    lines += [
        '### C. Protections for privacy, rights and confidentiality',
        '',
        '[DESCRIBE THE PROTECTIONS THAT APPLY: DE-IDENTIFICATION METHOD AND STANDARD, '
        'CONSENT TERMS AND ANY LIMITS THEY PLACE ON SECONDARY USE, IRB DETERMINATIONS, '
        'CERTIFICATES OF CONFIDENTIALITY, AND ANY TRIBAL OR OTHER COMMUNITY GOVERNANCE '
        'REQUIREMENTS.]',
        '',
    ]

    if facts.has_phi:
        lines += [
            '⚠ **This graph contains property names consistent with direct identifiers** '
            '(see Element 1). This subsection cannot be left as a placeholder: name the '
            'de-identification standard, the method, and who verifies it before release.',
            '',
        ]

    lines += [
        '### D. Licence',
        '',
        'Released data will be distributed under [LICENCE — e.g. CC BY 4.0 for open release, '
        'or the terms of a Data Use Agreement for controlled access]. The licence is recorded '
        'in each released RO-Crate\'s metadata, so the terms travel with the data.',
        '',
    ]

    return lines


def _access_prompt(facts: GraphFacts) -> List[str]:
    """What to say when nothing in the instance defines access terms."""
    lines = [
        '**No sharing terms have been defined in this SciDK instance, so this section could '
        'not be generated from your configuration.** It is the one element of a DMS plan that '
        'cannot be derived from the data themselves: what may be released depends on the '
        'consent under which it was collected and on institutional policy, neither of which '
        'is recorded in the graph.',
        '',
        '[DESCRIBE HOW THESE DATA WILL BE ACCESSED AND BY WHOM.] Choose the model that '
        'matches your consent terms:',
        '',
    ]
    lines += [
        f'- **{cfg.SHARING_MODE_LABELS[mode]}** — {cfg.SHARING_MODES[mode].split(".")[0]}.'
        for mode in ('open', 'registered_access', 'controlled_access', 'metadata_only', 'not_shared')
    ]
    per_property = (
        'or record per-property sharing modes against your entity types in the Labels UI'
        if facts.sharing_modes_supported else
        'or, once per-property sharing modes are available in the Labels UI, record them '
        'against your entity types'
    )
    lines += [
        '',
        f'To have this section generated in future drafts, either set '
        f'`{cfg.SETTING_SHARING_MODE}` under Settings → Publication to one of '
        f'`{"`, `".join(sorted(cfg.SHARING_MODES))}` — {per_property}, which produces a '
        f'property-by-property access statement instead of a single blanket one.',
        '',
    ]

    return lines


# ------------------------------------------------------------------ footer


def _footer(facts: GraphFacts) -> List[str]:
    """What was not generated, and why. Stated so an omission is not mistaken for completeness."""
    return [
        '---',
        '',
        '## Not generated by SciDK',
        '',
        'Two elements of the NIH DMS Policy are deliberately absent from this draft, because '
        'nothing in the knowledge graph can supply them and generated text would be a guess:',
        '',
        '- **Element 2: Related Tools, Software and/or Code** — [NAME THE SOFTWARE AND '
        'ANALYSIS CODE NEEDED TO USE THESE DATA, WHETHER IT IS OPEN OR PROPRIETARY, AND '
        'WHERE IT WILL BE DEPOSITED.]',
        '- **Element 6: Oversight of Data Management and Sharing** — [NAME WHO IS '
        'RESPONSIBLE FOR MONITORING THIS PLAN, HOW OFTEN COMPLIANCE IS REVIEWED, AND HOW '
        'PROBLEMS ARE ESCALATED.]',
        '',
        'Before submitting, search this document for `[` to find every remaining decision.',
        '',
    ]


# ------------------------------------------------------------------ render


def render_plan(facts: GraphFacts, generated_at: Optional[str] = None) -> str:
    """Render the draft DMS plan as markdown.

    Args:
        facts: Collected by
            :func:`plugins.nih_dms.graph_facts.collect_facts`.
        generated_at: Timestamp for the provenance line. Defaults to now, in UTC;
            pass one to make output reproducible in a test.

    Returns:
        A markdown document. Always non-empty, and never a static template: with
        no facts to report it says so, section by section, rather than filling in
        plausible prose.
    """
    stamp = generated_at or datetime.now(tz=timezone.utc).strftime('%Y-%m-%d %H:%M UTC')

    lines: List[str] = []
    lines += _preamble(facts, stamp)
    lines += _data_types_section(facts)
    lines += _standards_section(facts)
    lines += _preservation_section(facts)
    lines += _access_section(facts)
    lines += _footer(facts)

    return _tidy(lines)


def _tidy(lines: Iterable[str]) -> str:
    """Join lines, collapsing runs of blank lines so the markdown renders cleanly."""
    out: List[str] = []
    for line in lines:
        if not line.strip() and out and not out[-1].strip():
            continue
        out.append(line.rstrip())
    return '\n'.join(out).strip() + '\n'
